version: '3'

services:
  db:
    image: mongo
    command:
      - '--auth'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - ${DB_PERSIST_DIRECTORY}:/data/db
